In [0]:
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
%matplotlib inline
import seaborn as sns
import numpy as np
# import tensorflow as tf
from sklearn import metrics   #Additional scklearn functions
from sklearn.model_selection import GridSearchCV 

# from keras.models import Sequential 
# from keras.layers import Dense 
# from keras.utils import np_utils
# from sklearn.preprocessing import LabelEncoder
# from keras.utils.np_utils import to_categorical
# from sklearn.utils import shuffle

In [0]:
df = pd.read_csv('/content/drive/My Drive/airplane/train.csv')
test = pd.read_csv('/content/drive/My Drive/airplane/test.csv')
sample = pd.read_csv('/content/drive/My Drive/airplane/sample_submission.csv')

In [0]:
df.head()

Severity  ...  Accident_ID
0                Minor_Damage_And_Injuries  ...         7570
1                Minor_Damage_And_Injuries  ...        12128
2        Significant_Damage_And_Fatalities  ...         2181
3  Significant_Damage_And_Serious_Injuries  ...         5946
4        Significant_Damage_And_Fatalities  ...         9054

[5 rows x 12 columns]

In [0]:
df.Severity.value_counts()

Highly_Fatal_And_Damaging                  3049
Significant_Damage_And_Serious_Injuries    2729
Minor_Damage_And_Injuries                  2527
Significant_Damage_And_Fatalities          1695
Name: Severity, dtype: int64

In [0]:
df.Accident_Type_Code.value_counts()

4    2057
2    1791
3    1752
7    1276
6    1215
1    1171
5     738
Name: Accident_Type_Code, dtype: int64

In [0]:
df.isna().any()

Severity                   False
Safety_Score               False
Days_Since_Inspection      False
Total_Safety_Complaints    False
Control_Metric             False
Turbulence_In_gforces      False
Cabin_Temperature          False
Accident_Type_Code         False
Max_Elevation              False
Violations                 False
Adverse_Weather_Metric     False
Accident_ID                False
dtype: bool

In [0]:
target = df['Accident_ID']


In [0]:
df.drop(['Accident_ID'],inplace=True,axis=1)

In [0]:
accids=target

target = df['Severity']
df.drop(['Severity'],axis=1,inplace=True)

In [0]:
from sklearn.preprocessing import LabelEncoder

In [0]:
le = LabelEncoder()

In [0]:
target = le.fit_transform(target)

In [0]:
target

array([1, 1, 2, ..., 3, 1, 0])

In [0]:
df.head()

Safety_Score  Days_Since_Inspection  ...  Violations  Adverse_Weather_Metric
0     49.223744                     14  ...           3                0.424352
1     62.465753                     10  ...           2                0.352350
2     63.059361                     13  ...           3                0.003364
3     48.082192                     11  ...           1                0.211728
4     26.484018                     13  ...           2                0.176883

[5 rows x 10 columns]

In [0]:
df.columns

Index(['Safety_Score', 'Days_Since_Inspection', 'Total_Safety_Complaints',
       'Control_Metric', 'Turbulence_In_gforces', 'Cabin_Temperature',
       'Accident_Type_Code', 'Max_Elevation', 'Violations',
       'Adverse_Weather_Metric'],
      dtype='object')

In [0]:

df.dtypes

Safety_Score               float64
Days_Since_Inspection        int64
Total_Safety_Complaints      int64
Control_Metric             float64
Turbulence_In_gforces      float64
Cabin_Temperature          float64
Accident_Type_Code           int64
Max_Elevation              float64
Violations                   int64
Adverse_Weather_Metric     float64
dtype: object

In [0]:
df['Severity'] = target
df.drop(['Severity'],axis=1,inplace=True)

In [0]:
df.head()

Safety_Score  Days_Since_Inspection  ...  Violations  Adverse_Weather_Metric
0     49.223744                     14  ...           3                0.424352
1     62.465753                     10  ...           2                0.352350
2     63.059361                     13  ...           3                0.003364
3     48.082192                     11  ...           1                0.211728
4     26.484018                     13  ...           2                0.176883

[5 rows x 10 columns]

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [0]:
xtrain,xvalid,ytrain,yvalid = train_test_split(df,target,test_size=0.1
                                               ,shuffle=True,random_state=0)

In [0]:
# Gradient Boosting classifier

In [0]:
from sklearn.ensemble import GradientBoostingClassifier
gbk = GradientBoostingClassifier()
m1=gbk.fit(xtrain,ytrain)
p1 = m1.predict(xvalid)
print(accuracy_score(yvalid,p1,normalize=True))

0.869


In [0]:
import xgboost
from xgboost import XGBClassifier

In [0]:
xgb = xgboost.XGBClassifier(learning_rate=0.3,n_estimators=1250,
                            max_depth=5,objective='multi:softmax',
                            gamma=0)
m2 = xgb.fit(xtrain,ytrain)
p2 = m2.predict(xvalid)
print(accuracy_score(yvalid,p2,normalize=True))


0.963


In [0]:
p2 = pd.DataFrame(p2)

In [0]:
target = pd.DataFrame(target)
target[0].value_counts()

0    3049
3    2729
1    2527
2    1695
Name: 0, dtype: int64

In [0]:
mapdic = {0:'Highly_Fatal_And_Damaging',1:'Minor_Damage_And_Injuries',
          2:'Significant_Damage_And_Fatalities',
          3:'Significant_Damage_And_Serious_Injuries'}

In [0]:
p2f = p2[0].apply(lambda x : mapdic[x])

In [0]:
p2f = pd.DataFrame(p2f)

In [0]:
p2f.head()

0
0                Highly_Fatal_And_Damaging
1  Significant_Damage_And_Serious_Injuries
2                Highly_Fatal_And_Damaging
3  Significant_Damage_And_Serious_Injuries
4                Highly_Fatal_And_Damaging

In [0]:
test.head()

Safety_Score  Days_Since_Inspection  ...  Adverse_Weather_Metric  Accident_ID
0     19.497717                     16  ...                0.069692            1
1     58.173516                     15  ...                0.002777           10
2     33.287671                     15  ...                0.004316           14
3      3.287671                     21  ...                0.199990           17
4     10.867580                     18  ...                0.483696           21

[5 rows x 11 columns]

In [0]:
tids = test['Accident_ID']
test.drop(['Accident_ID'],axis=1,inplace=True)


KeyError: ignored

In [0]:
test.head()

Safety_Score  Days_Since_Inspection  ...  Violations  Adverse_Weather_Metric
0     19.497717                     16  ...           2                0.069692
1     58.173516                     15  ...           2                0.002777
2     33.287671                     15  ...           1                0.004316
3      3.287671                     21  ...           2                0.199990
4     10.867580                     18  ...           2                0.483696

[5 rows x 10 columns]

In [0]:
out1 = m2.predict(test)

In [0]:
out1

array([0, 2, 3, ..., 3, 3, 0])

In [0]:
out1 = pd.DataFrame(out1)

In [0]:
out1.head()

0
0  0
1  2
2  3
3  0
4  2

In [0]:
out1 = out1[0].apply(lambda x : mapdic[x])

In [0]:
out1 = pd.DataFrame(out1)

In [0]:
out1.head()

0
0                Highly_Fatal_And_Damaging
1        Significant_Damage_And_Fatalities
2  Significant_Damage_And_Serious_Injuries
3                Highly_Fatal_And_Damaging
4        Significant_Damage_And_Fatalities

In [0]:
out1 = out1.rename(columns={0:'Severity'})

In [0]:
d = {'Accident_ID':tids,'Severity':out1['Severity']}

o1 = pd.DataFrame(d)

In [0]:
o1.head()

Accident_ID                                 Severity
0            1                Highly_Fatal_And_Damaging
1           10        Significant_Damage_And_Fatalities
2           14  Significant_Damage_And_Serious_Injuries
3           17                Highly_Fatal_And_Damaging
4           21        Significant_Damage_And_Fatalities

In [0]:
o1.to_csv('/content/drive/My Drive/airplane/submission11.csv')

In [0]:
out2 = m2.predict(test)

In [0]:
out2

array([0, 2, 3, ..., 3, 3, 0])

In [0]:
out2 = pd.DataFrame(out2)

In [0]:
out2.head()

0
0  0
1  2
2  3
3  0
4  2

In [0]:
out2 = pd.DataFrame(out2[0].apply(lambda x: mapdic[x]))

In [0]:
out2.head()

0
0                Highly_Fatal_And_Damaging
1        Significant_Damage_And_Fatalities
2  Significant_Damage_And_Serious_Injuries
3                Highly_Fatal_And_Damaging
4        Significant_Damage_And_Fatalities

In [0]:
d2 = {'Accident_ID':tids,'Severity':out2[0]}

o2 = pd.DataFrame(d2)

In [0]:
o2.head()

Accident_ID                                 Severity
0            1                Highly_Fatal_And_Damaging
1           10        Significant_Damage_And_Fatalities
2           14  Significant_Damage_And_Serious_Injuries
3           17                Highly_Fatal_And_Damaging
4           21        Significant_Damage_And_Fatalities

In [0]:
o2.to_csv('/content/drive/My Drive/airplane/submission2.csv')

In [0]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=1000,
                             n_jobs=5)



clf.fit(xtrain,ytrain)
predrf = clf.predict(xvalid)
print(accuracy_score(predrf,yvalid,normalize=True))

0.923


In [0]:
out3 = clf.predict(test)

In [0]:
out3 = pd.DataFrame(out3)
out3.head()

0
0  0
1  2
2  3
3  0
4  2

In [0]:
out3[0] = out3[0].apply(lambda x : mapdic[x])

In [0]:
d3 = {'Accident_ID':tids,'Severity':out3[0]}
o3 = pd.DataFrame(d3)

In [0]:
o3.head()

Accident_ID                                 Severity
0            1                Highly_Fatal_And_Damaging
1           10        Significant_Damage_And_Fatalities
2           14  Significant_Damage_And_Serious_Injuries
3           17                Highly_Fatal_And_Damaging
4           21        Significant_Damage_And_Fatalities

In [0]:
o3.to_csv('/content/drive/My Drive/airplane/submission3.csv')

In [0]:
ytrain

array([1, 3, 0, ..., 3, 0, 1])

In [0]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()


xtrain = sc.fit_transform(xtrain)

In [0]:
xtrain

array([[-0.69710531,  1.72096061, -0.80165668, ...,  0.2601889 ,
        -0.97269409, -0.60660101],
       [ 0.3746196 , -0.54122882,  0.34792942, ...,  0.10806358,
        -0.01022622, -0.64680693],
       [-0.6574118 , -0.25845514,  0.7790242 , ..., -0.9662287 ,
        -0.97269409, -0.55714007],
       ...,
       [-0.64890605,  0.87263957, -0.37056189, ...,  0.04533125,
        -0.97269409,  2.44805498],
       [-1.41442384,  0.87263957, -0.22686363, ..., -0.18147346,
         0.95224165,  2.24768935],
       [ 0.43699513,  0.30709222, -0.08316537, ...,  0.68226723,
        -1.93516196, -0.59918233]])

In [0]:
ny = np_utils.to_categorical(target)

In [0]:
ny

array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]], dtype=float32)

In [0]:
nxtrain,nxvalid,nytrain,nyvalid = train_test_split(df,ny,test_size=0.1,random_state=0)

In [0]:
scc = StandardScaler()
nxtrain = scc.fit_transform(nxtrain)
nxvalid = scc.transform(nxvalid)

In [0]:



input_dim = len(df.columns.to_list())

nn = Sequential()
nn.add(Dense(10,input_dim=input_dim,activation='relu'))
nn.add(Dense(100,activation='relu'))
nn.add(Dense(75,activation='relu'))
nn.add(Dense(60,activation='relu'))
nn.add(Dense(50,activation='relu'))
nn.add(Dense(38,activation='relu'))
nn.add(Dense(25,activation='relu'))
nn.add(Dense(15,activation='relu'))
nn.add(Dense(8,activation='relu'))
nn.add(Dense(4,activation='softmax'))

nn.compile(loss = 'categorical_crossentropy' , optimizer = 'adam' , metrics = ['accuracy'] )

nn.fit(nxtrain,nytrain,epochs=100,batch_size=5)

scores = nn.evaluate(nxvalid,nyvalid)
print("\n%s: %.2f%%" % (nn.metrics_names[1], scores[1]*100))

Epoch 1/100
9000/9000 [==============================] - 6s 655us/step - loss: 0.9365 - acc: 0.5803
Epoch 2/100
9000/9000 [==============================] - 4s 445us/step - loss: 0.3714 - acc: 0.8603
Epoch 3/100
9000/9000 [==============================] - 4s 462us/step - loss: 0.2626 - acc: 0.9154
Epoch 4/100
9000/9000 [==============================] - 4s 492us/step - loss: 0.2438 - acc: 0.9277
Epoch 5/100
9000/9000 [==============================] - 4s 487us/step - loss: 0.2312 - acc: 0.9277
Epoch 6/100
9000/9000 [==============================] - 4s 437us/step - loss: 0.2145 - acc: 0.9333
Epoch 7/100
9000/9000 [==============================] - 4s 440us/step - loss: 0.2108 - acc: 0.9360
Epoch 8/100
9000/9000 [==============================] - 4s 452us/step - loss: 0.1991 - acc: 0.9373
Epoch 9/100
9000/9000 [==============================] - 4s 437us/step - loss: 0.2015 - acc: 0.9369
Epoch 10/100
9000/9000 [==============================] - 4s 426us/step - loss: 0.1942 - acc: 0.9390

In [0]:
test = pd.read_csv('/content/drive/My Drive/airplane/test.csv')

test.head()

Safety_Score  Days_Since_Inspection  ...  Adverse_Weather_Metric  Accident_ID
0     19.497717                     16  ...                0.069692            1
1     58.173516                     15  ...                0.002777           10
2     33.287671                     15  ...                0.004316           14
3      3.287671                     21  ...                0.199990           17
4     10.867580                     18  ...                0.483696           21

[5 rows x 11 columns]

In [0]:
test.drop(['Accident_ID'],axis=1,inplace=True)

In [0]:
test.head()

Safety_Score  Days_Since_Inspection  ...  Violations  Adverse_Weather_Metric
0     19.497717                     16  ...           2                0.069692
1     58.173516                     15  ...           2                0.002777
2     33.287671                     15  ...           1                0.004316
3      3.287671                     21  ...           2                0.199990
4     10.867580                     18  ...           2                0.483696

[5 rows x 10 columns]

In [0]:
nxtest = scc.transform(test)

In [0]:
nxtest

array([[-1.38732458,  0.86810876, -0.08043718, ...,  0.63363525,
        -0.01135143, -0.48703603],
       [ 1.0042925 ,  0.58572554, -0.51194997, ..., -0.18567029,
        -0.01135143, -0.66236478],
       [-0.53458744,  0.58572554, -0.51194997, ..., -1.51916925,
        -0.97515237, -0.65833236],
       ...,
       [-0.32281497,  0.30334233,  0.4949132 , ...,  0.49907716,
        -0.01135143, -0.64703272],
       [-0.19857512,  0.02095911,  1.07026359, ..., -0.8178201 ,
        -0.97515237, -0.65327511],
       [-0.36234583, -0.54380732, -0.79962516, ...,  0.41921074,
        -1.93895331, -0.6056862 ]])

In [0]:
predictions = nn.predict_classes(nxtest)
prediction_ = np.argmax(to_categorical(predictions), axis = 1)
prediction_ = le.inverse_transform(prediction_)

In [0]:
prediction_

array(['Highly_Fatal_And_Damaging', 'Significant_Damage_And_Fatalities',
       'Significant_Damage_And_Serious_Injuries', ...,
       'Significant_Damage_And_Serious_Injuries',
       'Significant_Damage_And_Serious_Injuries',
       'Highly_Fatal_And_Damaging'], dtype=object)

In [0]:
d4 = {'Accident_ID':tids,'Severity':prediction_}

out4 = pd.DataFrame(d4)

In [0]:
out4

Accident_ID                                 Severity
0               1                Highly_Fatal_And_Damaging
1              10        Significant_Damage_And_Fatalities
2              14  Significant_Damage_And_Serious_Injuries
3              17                Highly_Fatal_And_Damaging
4              21        Significant_Damage_And_Fatalities
...           ...                                      ...
2495        12484                Minor_Damage_And_Injuries
2496        12487  Significant_Damage_And_Serious_Injuries
2497        12488  Significant_Damage_And_Serious_Injuries
2498        12491  Significant_Damage_And_Serious_Injuries
2499        12493                Highly_Fatal_And_Damaging

[2500 rows x 2 columns]

In [0]:
out4.to_csv('/content/drive/My Drive/airplane/submission4.csv')
